# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c88f58c7024cf21aab0979c0e28964477656326fed8f9e636ddfb3b2b550b85a216fbf90da18d00e1c2d7426388c318ee40ce293171a0430febd4ef5418113c

test:
  secret_key_base: ec2b335c935a040ed8bdfd210e507ff8f276a9ee4d7098d60df6b342e2ad3ebc72299e37a948a0204308c49a6b9aa6863d1fd1bc64545bbee1866513cd287283

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
